### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by blopa**

### CODE REVIEW

**Comment by rafaelstz** [comment]
Hi @blopa, could you explain me why are you running as a root user?
It's not recommended running composer and the install process as a root user, it causes some issues related to the folders permission when trying to run in the browser.
Are you having issues when installing using the `./shell` command?

**Comment by blopa** [comment]
Hey Rafael.

Yes, I was facing a problem removing the index.php file - It only allowed me to do it if I was logged as root. I'm new to docker, so maybe I'm missing something. I tried to follow the exact steps in the README file and was only able after logging as root.

Best.

**Comment by rafaelstz** [comment]
Could you run the CURL command again? I have updated and tested, seems like it's working well now.

**Comment by blopa** [comment]
Hey Rafael.

Sadly, it still dosen't work :(

sudo

**Comment by rafaelstz** [comment]
Hi @blopa,
I worked on that today and it was fixed, you will be able to remove using a non-root user.
Thanks for your feedback, I appreciate it.

**Pull request closed without merging**
